from . import residencia
from . import proyecto_aso
from . import product_template
from . import contador
from . import proyecto_cobro_mensual
from . import account_journal
from . import cobro_consulta_wizard
from . import tipo_servicio_aso
from . import account_move_line
from . import residencia_report